
- url: https://api.greenhouse.io/v1/boards/robinhood/jobs
  name: Robinhood
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: &id001
    - mon
    - tue
    - wed
    - thu
    - fri
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/mongodb/jobs
  name: MongoDB
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/nexhealth/jobs
  name: NexHealth
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/okta/jobs
  name: Okta
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/axon/jobs
  name: Axon
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/flex/jobs
  name: Flex
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://boards-api.greenhouse.io/v1/boards/Airbnb/jobs
  name: Airbnb
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://boards-api.greenhouse.io/v1/boards/Coupang/jobs
  name: Coupang
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/purestorage/jobs
  name: PureStorage
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/samsara/jobs
  name: Samsara
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/stripe/jobs
  name: Stripe
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/zscaler/jobs
  name: Zscaler
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/xai/jobs
  name: xAI
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/twilio/jobs
  name: Twilio
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://boards-api.greenhouse.io/v1/boards/stubhubinc/jobs
  name: Stubhub
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://careers.datadoghq.com/all-jobs/?s=software%20engineer
  name: datadog
  enabled: false
  pattern: https://careers.datadoghq.com/detail/**
  schedule:
    name: Every 5 mins checck daily
    days: *id001
    startTime: 08:00
    intervalMinutes: 5.0
    timezone: America/Denver
- url: https://careers.godaddy/jobs/search?page=1&query=engineer&country_codes%5B%5D=US
  name: GoDaddy
  enabled: true
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://careers.confluent.io/jobs/united_states-engineering?engineering=engineering
  name: Confluent
  enabled: true
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://www.uber.com/us/en/careers/list/?query=engineer&location=USA-California-San%20Francisco&location=USA-California-Los%20Angeles&location=USA-California-Sunnyvale&location=USA-California-Culver%20City&location=USA-New%20York-New%20York&location=USA-Washington-Seattle&location=USA-Illinois-Chicago&location=USA-Texas-Dallas&location=USA-Florida-Miami&location=USA-Arizona-Phoenix&location=USA-Georgia-Atlanta&location=USA-District%20of%20Columbia-Washington
  name: Uber
  enabled: true
  type: uber
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://careers.adobe.com/us/en/search-results?keywords=engineer
  name: Adobe
  enabled: true
  type: adobe
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://careers.cisco.com/global/en/search-results?keywords=%22software%20engineer%22&s=1
  name: Cisco
  enabled: true
  type: cisco
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://jobs.paloaltonetworks.com/en/search-jobs?k=software%20engineer&l=United+States
  name: Palo Alto Networks
  enabled: true
  type: general
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://dataminr.wd12.myworkdayjobs.com/en-US/Dataminr/?q=engineer
  name: Dataminr
  enabled: true
  type: workday
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://careers.docusign.com/api/jobs?categories=Engineering%7CIT%20Infrastructure%20%26%20Operations&page=1&locations=San%20Francisco,California,United%20States%7CSeattle,Washington,United%20States&sortBy=relevance&descending=false&internal=false
  name: Docusign
  enabled: true
  type: docusign
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://jobs.ashbyhq.com/notion
  name: Notion
  enabled: true
  type: ashby
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://openai.com/careers/search/?q=engineer&l=e8062547-b090-4206-8f1e-7329e0014e98%2C07ed9191-5bc6-421b-9883-f1ac2e276ad7%2C16c48b76-8036-4fe3-a18f-e9d357395713%2C6252b4ed-714d-469a-a970-7a13101bac9d%2Cbbd9f7fe-aae5-476a-9108-f25aea8f6cd2
  name: OpenAI
  enabled: true
  type: openai
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
