site_schedules:
- url: https://api.greenhouse.io/v1/boards/airbnb/jobs
  name: airbnb
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: &id001
    - mon
    - tue
    - wed
    - thu
    - fri
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/airtable/jobs
  name: airtable
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/coinbase/jobs
  name: coinbase
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/coreweave/jobs
  name: coreweave
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/coupang/jobs
  name: coupang
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/datadog/jobs
  name: datadog
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: Every 5 mins checck daily
    days: &id002
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    startTime: 08:00
    intervalMinutes: 5.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/figma/jobs
  name: figma
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/lyft/jobs
  name: lyft
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/pinterest/jobs
  name: pinterest
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/robinhood/jobs
  name: robinhood
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/rubrik/jobs
  name: rubrik
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/stubhubinc/jobs
  name: stubhub
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: Every 5 mins checck daily
    days: *id002
    startTime: 08:00
    intervalMinutes: 5.0
    timezone: America/Denver
- url: https://api.greenhouse.io/v1/boards/thetradedesk/jobs
  name: theTradeDesk
  enabled: true
  type: greenhouse
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://bloomberg.avature.net/careers/SearchJobs/engineer?1845=%5B162619%2C162522%2C162483%2C162484%2C162552%2C162508%2C162520%2C162535%5D&1845_format=3996&1686=%5B57029%5D&1686_format=2312&listFilterMode=1&jobRecordsPerPage=12&jobOffset=0
  name: Bloomberg
  enabled: true
  type: avature
  scrapeProvider: spidercloud
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://careers.confluent.io/jobs/united_states-engineering?engineering=engineering
  name: Confluent
  enabled: true
  type: general
  scrapeProvider: spidercloud
  schedule:
    name: Every 5 mins checck daily
    days: *id002
    startTime: 08:00
    intervalMinutes: 5.0
    timezone: America/Denver
- url: https://careers.snap.com/jobs
  name: snapchat
  enabled: true
  type: general
  scrapeProvider: spidercloud
  pattern: https://careers.snap.com/job**
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://jobs.ashbyhq.com/lambda
  name: lambda
  enabled: true
  type: general
  scrapeProvider: spidercloud
  pattern: https://jobs.ashbyhq.com/lambda/*
  schedule:
    name: weekdays 9:30am
    days: *id001
    startTime: 09:30
    intervalMinutes: 1440.0
    timezone: America/Denver
- url: https://www.github.careers/careers-home/jobs?keywords=engineer&sortBy=relevance&limit=100
  name: Github
  enabled: true
  type: general
  scrapeProvider: spidercloud
  schedule:
    name: Every 5 mins checck daily
    days: *id002
    startTime: 08:00
    intervalMinutes: 5.0
    timezone: America/Denver
